/**
 * @class
 * @memberOf next2d.events
 * @extends  Event
 */
class MouseEvent extends Event
{

    /**
     * MouseEvent オブジェクトは、マウスイベントが発生するたびにイベントフローに送出されます。
     * 通常、マウスイベントは、マウスやトラックボールなど、ポインターを使用したユーザー入力デバイスによって生成されます。
     *
     * A MouseEvent object is dispatched into the event flow whenever mouse events occur.
     * A mouse event is usually generated by a user input device,
     * such as a mouse or a trackball, that uses a pointer.
     *
     * @param {string}  type
     * @param {boolean} [bubbles=true]
     * @param {boolean} [cancelable=false]
     * @param {number}  [local_x=NaN]
     * @param {number}  [local_y=NaN]
     *
     * @constructor
     * @public
     */
    constructor (
        type, bubbles = true, cancelable = false,
        local_x = NaN, local_y = NaN
    ) {

        super(type, bubbles, cancelable);

        return new Proxy(this, {
            "get": function (object, name)
            {
                if (name in object) {
                    return object[name];
                }

                if (Util.$event && name in Util.$event) {
                    return Util.$event[name];
                }

                return undefined;
            }
        });

    }

    /**
     * 指定されたクラスのストリングを返します。
     * Returns the string representation of the specified class.
     *
     * @return  {string}
     * @default [class MouseEvent]
     * @method
     * @static
     */
    static toString()
    {
        return "[class MouseEvent]";
    }

    /**
     * @description 指定されたクラスの空間名を返します。
     *              Returns the space name of the specified class.
     *
     * @member  {string}
     * @default next2d.events:MouseEvent
     * @const
     * @static
     */
    static get namespace ()
    {
        return "next2d.events:MouseEvent";
    }

    /**
     * @description 指定されたオブジェクトのストリングを返します。
     *              Returns the string representation of the specified object.
     *
     * @return {string}
     * @method
     * @public
     */
    toString ()
    {
        return this.formatToString(
            "MouseEvent",
            "type", "bubbles", "cancelable", "eventPhase",
            "localX", "localY", "stageX", "stageY",
            "ctrlKey", "altKey", "shiftKey", "buttonDown",
            "delta", "commandKey", "controlKey", "clickCount"
        );
    }

    /**
     * @description 指定されたオブジェクトの空間名を返します。
     *              Returns the space name of the specified object.
     *
     * @member  {string}
     * @default next2d.events:MouseEvent
     * @const
     * @public
     */
    get namespace ()
    {
        return "next2d.events:MouseEvent";
    }

    /**
     * @description click イベントオブジェクトの type プロパティ値を定義します。
     *              Defines the value of the type property of a click event object.
     *
     * @return {string}
     * @default click
     * @const
     * @static
     */
    static get CLICK ()
    {
        return "click";
    }

    /**
     * @description dblclick イベントオブジェクトの type プロパティ値を定義します。
     *              Defines the value of the type property of a dblclick event object.
     *
     * @return {string}
     * @default dblclick
     * @const
     * @static
     */
    static get DOUBLE_CLICK ()
    {
        return "dblclick";
    }

    /**
     * @description mouseDown イベントオブジェクトの type プロパティ値を定義します。
     *              Defines the value of the type property of a mouseDown event object.
     *
     * @return {string}
     * @default mouseDown
     * @const
     * @static
     */
    static get MOUSE_DOWN ()
    {
        return "mouseDown";
    }

    /**
     * @description mouseMove イベントオブジェクトの type プロパティ値を定義します。
     *              Defines the value of the type property of a mouseMove event object.
     *
     * @return {string}
     * @default mouseMove
     * @const
     * @static
     */
    static get MOUSE_MOVE ()
    {
        return "mouseMove";
    }

    /**
     * @description mouseOut イベントオブジェクトの type プロパティ値を定義します。
     *              Defines the value of the type property of a mouseOut event object.
     *
     * @return {string}
     * @default mouseOut
     * @const
     * @static
     */
    static get MOUSE_OUT ()
    {
        return "mouseOut";
    }

    /**
     * @description mouseOver イベントオブジェクトの type プロパティ値を定義します。
     *              Defines the value of the type property of a mouseOver event object.
     *
     * @return {string}
     * @default mouseOver
     * @const
     * @static
     */
    static get MOUSE_OVER ()
    {
        return "mouseOver";
    }

    /**
     * @description mouseUp イベントオブジェクトの type プロパティ値を定義します。
     *              Defines the value of the type property of a mouseUp event object.
     *
     * @return {string}
     * @default mouseUp
     * @const
     * @static
     */
    static get MOUSE_UP ()
    {
        return "mouseUp";
    }

    /**
     * @description mouseWheel イベントオブジェクトの type プロパティ値を定義します。
     *              Defines the value of the type property of a mouseWheel event object.
     *
     * @return {string}
     * @default mouseWheel
     * @const
     * @static
     */
    static get MOUSE_WHEEL ()
    {
        return "mouseWheel";
    }

    /**
     * @description rollOut イベントオブジェクトの type プロパティ値を定義します。
     *              Defines the value of the type property of a rollOut event object.
     *
     * @return {string}
     * @default rollOut
     * @const
     * @static
     */
    static get ROLL_OUT ()
    {
        return "rollOut";
    }

    /**
     * @description rollOver イベントオブジェクトの type プロパティ値を定義します。
     *              Defines the value of the type property of a rollOver event object.
     *
     * @return {string}
     * @default rollOver
     * @const
     * @static
     */
    static get ROLL_OVER ()
    {
        return "rollOver";
    }
}