export type IBlendMode =
    | "normal"
    | "layer"
    | "multiply"
    | "screen"
    | "lighten"
    | "darken"
    | "difference"
    | "add"
    | "subtract"
    | "invert"
    | "alpha"
    | "erase"
    | "overlay"
    | "hardlight";
