name: Player Test
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: browser-actions/setup-chromium@latest
      - run: chrome --version
      - run: npm install
      - run: npm test