name: Player Test
on:
  push:
    branches:
      - develop
jobs:
  browsers-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: browser-actions/setup-chromium@latest
      - uses: browser-actions/setup-firefox@latest
      - run: |
          sudo safaridriver --enable
          safaridriver -p 0 &
      - run: npm install
      - run: npm test