name: Publish Package

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm@latest
      - run: npm install
      - run: npm run publish:dist
      - run: npm publish
        working-directory: ./dist/src
      - run: npm publish
        working-directory: ./dist/packages/cache
      - run: npm publish
        working-directory: ./dist/packages/core
      - run: npm publish
        working-directory: ./dist/packages/display
      - run: npm publish
        working-directory: ./dist/packages/events
      - run: npm publish
        working-directory: ./dist/packages/filters
      - run: npm publish
        working-directory: ./dist/packages/geom
      - run: npm publish
        working-directory: ./dist/packages/media
      - run: npm publish
        working-directory: ./dist/packages/net
      - run: npm publish
        working-directory: ./dist/packages/render-queue
      - run: npm publish
        working-directory: ./dist/packages/renderer
      - run: npm publish
        working-directory: ./dist/packages/text
      - run: npm publish
        working-directory: ./dist/packages/texture-packer
      - run: npm publish
        working-directory: ./dist/packages/ui
      - run: npm publish
        working-directory: ./dist/packages/webgl
      - run: npm publish
        working-directory: ./dist/packages/webgpu
      - run: npm run clean