name: Publish Package

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm@latest
      - run: npm install
      - run: npm run publish:dist
      - name: Publish packages
        run: |
          find ./dist -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \; | while read dir; do
            npm publish --workspace="${dir}"
          done
      - run: npm run clean